apiVersion: v1
kind: Service
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
spec:
  type: {{ .ServiceType }}
  
  selector:
    app: {{ .AppName }}
  
  ports:
    - name: http
      protocol: TCP
      port: {{ .ServicePort }}
      targetPort: {{ .ContainerPort }}
